window.__SUPABASE_URL__="https://zlllebsjtgihsxhcmcvb.supabase.co";
window.__SUPABASE_ANON_KEY__="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsbGxlYnNqdGdpaHN4aGNtY3ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3NDQxMjQsImV4cCI6MjEwMTMyMDEyNH0.Q6PuA6nvTI__DEB0i7akLusljjjeYu_0IxQICOc5oSQ";
window.__SUPABASE_ANON__=window.__SUPABASE_ANON_KEY__;
window.__SUPABASE_PUBLISHABLE_KEY__="sb_publishable_dgxHXsTRw735YyS5FtL1SA_vQgxEXMF";
window.__VAPID_PUBLIC_KEY__="BP4RL2RLsbcX3WetqBoYMHmksNprWzcfubLegJ8VDbgTH0_T369YNTNAMWA5YbrxylWJwSe7MDCyVOOQ0Jfm7Cw";
