#!/bin/bash
set -e
cd "$(dirname "$0")/.."
echo "=== Nylah OS APK Build - goal_f740d0ec1e6b ==="

# Web build - Hatch driver required for TS spaces
echo "[1/4] Building web..."
HATCH_SPACES_BUILD_DRIVER=1 npm run build || bun run build || npm run build:client

# Capacitor sync
echo "[2/4] Capacitor copy..."
if ! npx cap copy android 2>/dev/null; then
  npx cap copy || echo "cap copy skipped - no android folder yet"
fi

# Android assemble if SDK present
if [ -d "android" ] && [ -f "android/gradlew" ]; then
  echo "[3/4] Gradle assembleDebug..."
  cd android
  if ./gradlew assembleDebug; then
    echo "APK built: $(ls -lh app/build/outputs/apk/debug/app-debug.apk)"
    ls -lh app/build/outputs/apk/debug/*.apk || true
  else
    echo "Gradle missing SDK or build failed - scaffold kept, web bundle ready."
    echo "To build manually: cd android && ./gradlew assembleDebug"
  fi
  cd ..
else
  echo "[3/4] No android folder / gradlew - scaffold mode"
  echo "Run once: npx cap add android"
  echo "Then: npx cap copy && cd android && ./gradlew assembleDebug"
  mkdir -p android/app/src/main || true
  cat > android/README.md << 'READMEEOF'
# Android scaffold (no SDK in this environment)

This folder would be generated by:

  npx cap add android
  npx cap copy android
  cd android && ./gradlew assembleDebug

Output APK: app/build/outputs/apk/debug/app-debug.apk

Primary update strategy (no APK reinstall needed):
  capacitor.config.ts server.url = https://nylah-os.netlify.app
  -> updates = deploy new zip to Netlify.

If you bundle offline: UpdaterBanner + updater.ts handles version.json check.
READMEEOF
fi

echo "[4/4] version.json check"
cat public/version.json || cat client/public/version.json || echo '{"version":"1.0.0"}'

echo "=== APK scaffolding done - coordinator zips, no zip yet per task ==="
